### PR TITLE
Python 3.11

### PR DESCRIPTION
**Pull request by sdaves**
Adds python 3.11 support with latest packages and keep exiting versions functioning

### CODE REVIEW

**Comment by suned** [comment]
Awesowe, happy to merge this. I think the the failing tests is because `asynctest` depends on a now removed function in asyncio. Its also pretty old. Probably the "correct" solution would be to remove it and replace it with the async features in `unittest.mock`.

**Comment by sdaves** [comment]
@suned The unittest.mock migration is complete. I disabled the test runner for 3.7, as it doesn't support the new test api, but the 3.7 runtime still functions as expected.

**Comment by suned** [comment]
> The unittest.mock migration is complete. I disabled the test runner for 3.7, as it doesn't support the new test api, but the 3.7 runtime still functions as expected.

🙌

**Review by suned — APPROVED** [review]

**Comment by suned** [comment]
@sdaves I went ahead and pulled the trigger on this. Hit a a bit of a snag trying to release it though: https://github.com/suned/pfun/actions/runs/6923101459/job/18831199451 I'll take a look ASAP

**Comment by suned** [comment]
@sdaves Its out as 0.13.2: https://pypi.org/project/pfun/ 🥳 

I had to remove the git dependency you added on asyncpg as pypi apparently doesn't allow that. I fixed the version to 0.28, the latest version that supports Python 3.7. I'm very open to dropping support for Python 3.7 entirely since its past end-of-life. I hope that particular change wasn't super important to you 😅

**Pull request merged**
