### PR TITLE
fix (mypy-plugin): tuple object does not support item assignment

### LINKED ISSUE #62: mypy plugin error: 'tuple' object does not support item assignment
Probably something I'm doing wrong (ie not informing types arguments of Either), but...

mypy `MethodContext.default_return_type.args` may return a `tuple` instead of a `list`.

Raising ''TypeError: 'tuple' object does not support item assignment" for code above

```python
return_type = context.default_return_type
return_type_args: return_type.args
...
return_type_args[0]: _combine_environments(r1, r2)
```

We could expect that if isn't a list dev made something wrong - like I did - but this and similar assignments may cause unintended side effects  :thinking:

### PR DESCRIPTION
**Pull request by hugosenari**
**What** it solves:

fix #62: 
```

/pfun/mypy_plugin.py", line 396, in _combine_hook
    ret_type_args[1] = combined_error_type
TypeError: 'tuple' object does not support item assignment

```

**How** it was solved:
creatings a new list from `.args`

### CODE REVIEW

**Comment by suned** [comment]
Nice catch! Do you have a the code that produced the error in the first place? I'd like to add a regression test to `tests/test_mypy_plugin.yaml`. If you don't want to touch that file, maybe you can add a snippet in #62, I'll do it myself

**Comment by suned** [comment]
I realised the error only occurs when using mypy 0.800. I suppose they changed the plugin api without bumping a major version, which is unfortunate.

I bumped the mypy version, in order that we simply test against the newest version. That required fixing one other test.

**Comment by hugosenari** [comment]
if they use semantic versioning, `0.xx` is unstable.
Means it may happen until '1.x'

What are versioning/stability strategy of mypy?

**Comment by suned** [comment]
I think you are right that they use semantic versioning, I suppose it is expected. The trouble is that MyPy is a somewhat special "dependency" as its not installed with pfun, its something users will install themselves if they need it. This means that unlike a regular dependency, we don't really control which version of pfun will be used. It might make sense to write somewhere in the documentation what version(s) of MyPy we test against.

**Pull request merged**
